{
  lib,
  stdenv,
  fetchurl,
  autoPatchelfHook,
  dbus,
  libcap,
  libgcrypt,
  libgpg-error,
  lz4,
  xz,
  zstd,
  systemd,
  unzip,
  gcc,
  wayland,
  libxkbcommon,
  libGL,
  vulkan-loader,
  fontconfig,
  freetype,
  expat,
  glib,
  libx11,
  libxcursor,
  libxi,
  libxrandr,
  libxext,
  libxfixes,
  libxrender,
  libxcb,
  # Upstream release feed: https://cdn.notesy.ink/beta/latest.json
  # The download URL is derived dynamically as
  # `${baseUrl}/${channel}/${version}/${assetFile}` so bumping `version`
  # (or switching `channel`/`assetKind`) needs no URL edits — only the
  # pinned hashes below change. Pinned instead of fetching latest.json at
  # eval time so the derivation evaluates purely (required for flakes) and
  # a given commit always builds the same binary. Bump via ./update.sh.
  # If you override `version`, also pass `srcHash` and `programSha256`
  # unless the new version already has an entry in `hashes`.
  channel ? "beta",
  baseUrl ? "https://cdn.notesy.ink",
  version ? "0.1.14-beta.1",
  # Linux asset kind from the feed: "tar" (default) or "zip".
  assetKind ? "tar",
  # Explicit overrides win over derived defaults.
  srcUrl ? null,
  srcHash ? null,
  programPath ? null,
  programSha256 ? null,
}:
let
  system = stdenv.hostPlatform.system;
  # Upstream asset stem per Nix system. Add new systems here as upstream
  # ships them; hashes for the new system go in `hashes` below.
  assetStems = {
    x86_64-linux = "linux-x86_64";
    aarch64-linux = "linux-aarch64";
  };
  supportedSystems = builtins.attrNames assetStems;
  assetStem =
    assetStems.${system}
      or (throw "notesy: unsupported system '${system}'. Supported: ${lib.concatStringsSep ", " supportedSystems}.");
  assetFile =
    if assetKind == "tar" then
      "notesy-${version}-${assetStem}.tar.gz"
    else if assetKind == "zip" then
      "notesy-${version}-${assetStem}.zip"
    else
      throw "notesy: unknown assetKind '${assetKind}'. Expected \"tar\" or \"zip\".";
  # Pinned hashes per version/system, generated by ./update.sh from the
  # upstream feed and stored in versions.json (kept out of the .nix so the
  # updater never has to edit Nix code). `zip` is null where that
  # version's zip hash was never recorded — pass `srcHash` explicitly to
  # use it. `programSha256` may be null if the feed omits it.
  hashes = builtins.fromJSON (builtins.readFile ./versions.json);
  pinnedVersions = builtins.attrNames hashes;
  versionHashes =
    hashes.${version}
      or (throw "notesy: unknown version '${version}'. Pinned: ${lib.concatStringsSep ", " pinnedVersions}. Run ./update.sh ${version} or pass `srcHash`/`programSha256` explicitly.");
  systemHashes =
    versionHashes.${system}
      or (throw "notesy: version '${version}' has no pinned hashes for '${system}'. Run ./update.sh ${version} or pass `srcHash`/`programSha256` explicitly.");
  defaults = {
    srcUrl = "${baseUrl}/${channel}/${version}/${assetFile}";
    srcHash =
      if assetKind == "tar" then
        systemHashes.tar
      else if systemHashes.zip != null then
        systemHashes.zip
      else
        throw "notesy: no pinned `zip` hash for version '${version}' on '${system}'. Pass `srcHash` explicitly or use assetKind = \"tar\".";
    programPath = systemHashes.programPath;
    programSha256 = systemHashes.programSha256;
  };
  srcUrl_ = if srcUrl != null then srcUrl else defaults.srcUrl;
  srcHash_ = if srcHash != null then srcHash else defaults.srcHash;
  programPath_ = if programPath != null then programPath else defaults.programPath;
  programSha256_ = if programSha256 != null then programSha256 else defaults.programSha256;
  # winit-0.30 dlopen()s these at runtime (Wayland/X11/GL);
  # invisible to ldd, so they must also be in runtimeDependencies.
  # Linux-only: guarded so a future darwin asset doesn't try to evaluate
  # ELF/Wayland/systemd closure members.
  guiRuntime = lib.optionals stdenv.isLinux [
    wayland
    libxkbcommon
    libGL
    vulkan-loader
    fontconfig
    freetype
    expat
    glib
    libx11
    libxcursor
    libxi
    libxrandr
    libxext
    libxfixes
    libxrender
    libxcb
  ];
  linuxOnly = lib.optionals stdenv.isLinux [
    dbus
    systemd
  ];
in
stdenv.mkDerivation {
  pname = "notesy";
  inherit version;

  src = fetchurl {
    url = srcUrl_;
    sha256 = srcHash_;
  };

  nativeBuildInputs =
    lib.optional stdenv.isLinux autoPatchelfHook ++ lib.optional (lib.hasSuffix ".zip" srcUrl_) unzip;

  buildInputs = [
    stdenv.cc.cc.lib
    libcap
    libgcrypt
    libgpg-error
    lz4
    xz
    zstd
    gcc
  ]
  ++ linuxOnly
  ++ guiRuntime;

  # autoPatchelfHook only patches DT_NEEDED; winit uses dlopen(),
  # so force these into RPATH unconditionally.
  runtimeDependencies = guiRuntime;

  # The zip needs an explicit unzip; the tarball unpacks with tar.
  # Dispatch on extension so both old (zip-only) and new (tar+zip)
  # schemas work.
  unpackPhase = ''
    runHook preUnpack

    if [[ "$src" == *.zip ]]; then
      unzip -q "$src"
    else
      tar xf "$src"
    fi

    runHook postUnpack
  '';

  installPhase = ''
    runHook preInstall

    ${lib.optionalString (programSha256_ != null && programSha256_ != "") ''
      echo "checking unpacked program against pinned programSha256..."
      echo "${programSha256_}  ${programPath_}" | sha256sum -c -
    ''}

    install -Dm755 ${programPath_} $out/bin/notesy
    install -Dm644 notesy.desktop $out/share/applications/notesy.desktop

    mkdir -p $out/share/icons
    cp -r hicolor $out/share/icons/

    runHook postInstall
  '';

  meta = with lib; {
    description = "Plain markdown notes in a fast native app";
    homepage = "https://notesy.ink/";
    license = licenses.unfree;
    platforms = supportedSystems;
    sourceProvenance = with sourceTypes; [ binaryNativeCode ];
  };
}
